#!/usr/bin/env php
<?php
declare(strict_types=1);

// Error reporting
error_reporting(E_ALL);
ini_set('display_errors', 'On');
ini_set('display_startup_errors', 'On');
ini_set('log_errors', 'On');

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Studio24\Apollo\Command\BuildCommand;
use Studio24\Apollo\Command\WatchCommand;

$application = new Application();

$application->add(new BuildCommand());
$application->add(new WatchCommand());

$application->run();